# Generated by Django 6.0 on 2026-01-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_invoice_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
