# Generated by Django 6.0 on 2026-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('OPD', 'Out Patient'), ('IPD', 'In Patient')], default='OPD', max_length=3),
        ),
    ]
