# Generated by Django 6.0 on 2026-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(default='Runda,Kenya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opening_hours',
            field=models.CharField(default='9am - 7pm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(default='25496587545', max_length=20),
            preserve_default=False,
        ),
    ]
