# Generated by Django 6.0 on 2026-01-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacy_options_drug_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='medicine_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
