# Generated by Django 6.0 on 2026-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_druggroup_drug_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugpurchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
