# Generated by Django 6.0 on 2026-02-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_drugpurchase_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugpurchase',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='drugpurchase',
            name='tax_percentage',
        ),
    ]
