# Generated by Django 6.0 on 2026-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_drugpurchase_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.CharField(choices=[('Grams', 'Grams'), ('ML', 'ML'), ('MG', 'MG'), ('%', '%')], max_length=50),
        ),
    ]
